name: deploy
on: 
    workflow_dispatch:
        inputs:
            name:
              type: string
              description: project name
              required: true
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
         version: 8.3.1

      - name: Install deps
        run: pnpm nx run install

      - name: Build
        run: pnpm nx run ${{ github.event.inputs.name }}:build

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        run: pnpm nx run ${{ github.event.inputs.name }}:deploy
    