name: deploy fitness server

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
         version: 8.3.1

      - name: pnpm install and build
        working-directory: ./apps/server
        run: |
          pnpm install
          pnpm build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: fitness-server
          path: apps/server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: fitness-server

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        env: # Add environment variables here
          NODE_VERSION: 12       
          PRE_BUILD_COMMAND: "npm install -g prisma"   
          CUSTOM_BUILD_COMMAND: "npm install @prisma/client && npm run build"               
          POST_BUILD_COMMAND: "npm install @prisma/client"      
        with:
          app-name: 'fitness-server'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BB3E37731C90487D9879EA80FE72217F }}
          package: .
